entryPoints:
  web:
    address: ":8081"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":8443"

providers:
  file:
    filename: /etc/traefik/dynamic/dynamic.yml
    watch: true

log:
  level: INFO

accessLog: {}

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus: {}

